#!/usr/bin/env python3
"""Exact full-dimensional ordinary-square homotopy ledger for q=19, ell=4.

Every official structured row admits a K-dimensional ordinary F_19-linear
slice inside the fresh vinegar subspace.  The complete residual system is then
K quadratics in K variables.  This script prices the finite-cardinality
symbolic-homotopy route with the same conservative A-extension arithmetic
schedule used in the paper and the accepted-full-Jacobian success theorem.
"""
from __future__ import annotations
import json, math
from decimal import Decimal, getcontext
from fractions import Fraction
from pathlib import Path
getcontext().prec=120
ROOT=Path(__file__).resolve().parent
Q=19; D=4; AS=Q**D; G4=6081
LEVELS=[("I",143,50,33,(74,74)),("III",207,70,47,(110,114)),("V",272,90,59,(138,146))]

def log2f(x:Fraction)->float:
 return float((Decimal(x.numerator).ln()-Decimal(x.denominator).ln())/Decimal(2).ln())
def extdeg(E:int)->int:
 r=1
 while AS**r<E:r+=1
 return r
def human(n:int)->str:
 for z,u in [(2**100,"QiB"),(2**90,"RiB"),(2**80,"YiB"),(2**70,"ZiB"),(2**60,"EiB"),(2**50,"PiB"),(2**40,"TiB"),(2**30,"GiB")]:
  if n>=z:return f"{n/z:.3f} {u}"
 return f"{n} B"
def main():
 rows=[]
 for level,ref,K,n,ts in LEVELS:
  B=2**K; Bp=B*(1+K//2)
  L=K*(K+1)//2+2*K*(K*(K+1)//2+K+1)
  H=L+2*K+K*K
  E=max(2*K,8*B*B)
  r=extdeg(E); cr=2*r-1
  alpha=Fraction((AS-1)**n,AS**n)
  eta=Fraction(Q**K-1,Q**K)+Fraction(1,Q)
  success=(alpha-eta/Fraction(Q-1,1))**2/(1+eta)
  hom=cr*B*Bp*H
  filt=cr*B*L
  total=Fraction(8*G4,7)*(K*hom+filt)/success
  by=math.ceil(D*r*math.log2(Q)/8)
  out=(K+2)*B*by
  rows.append({"level":level,"reference":ref,"K":K,"B":B,"B_plus":Bp,"L":L,"H":H,
    "threshold_E":E,"extension_degree_r":r,"pointwise_factor":cr,
    "eta_numerator":eta.numerator,"eta_denominator":eta.denominator,
    "root_success_numerator":success.numerator,"root_success_denominator":success.denominator,
    "root_success_decimal":float(success),"expected_trials_upper":float(1/success),
    "AXN_numerator":total.numerator,"AXN_denominator":total.denominator,
    "bits":log2f(total),"margin":ref-log2f(total),
    "packed_bytes_per_element":by,"packed_output_bytes":out,"packed_output_human":human(out),
    "spectrum_tail_log2_by_shape":[]})
 data={"field":"F_19; arithmetic conservatively grouped through A=F_{19^4}",
       "scope":"Deterministic slice existence; random-XOF aggregate-spectrum tail; no A-linearity, fixed core, output projection, or selected Macaulay degree.","levels":rows}
 (ROOT/'ordinary_square_certificate.json').write_text(json.dumps(data,indent=2)+'\n')
 md=["# Exact full-dimensional ordinary-square certificate","", "Generated by `build_ordinary_square_certificate.py`.","",
 "| Level | K | extension degree over A | exponent | margin | root success | packed output ceiling |",
 "|---:|---:|---:|---:|---:|---:|---:|"]
 for r in rows: md.append(f"| {r['level']} | {r['K']} | {r['extension_degree_r']} | {r['bits']:.6f} | {r['margin']:.6f} | {r['root_success_decimal']:.9f} | {r['packed_output_human']} |")
 md += ["", "The Level-I row is above the 143-bit reference and is retained only as a fully unconditional structural fallback. Levels III and V are below their references with large arithmetic margins, although their straightforward output parametrizations are astronomically large."]
 (ROOT/'ORDINARY_SQUARE_CERTIFICATE.md').write_text('\n'.join(md)+'\n')
 for r in rows:print(r['level'],f"{r['bits']:.9f}",f"margin={r['margin']:.6f}",r['packed_output_human'])
if __name__=='__main__':main()
