#!/usr/bin/env python3
"""Exact biased-product anti-concentration bounds for selected eigenblock cores.

For each recommended core, the chosen equation rows are assigned to the first
`count` public base forms in each active eigenblock family, exactly as in the
witness certificate.  The core-Jacobian determinant is linear in each selected
row, so its degree in the independent coefficient block of public base form i
is the number of selected families containing row i.  Coordinate separation
makes the scalar coordinates in distinct base-form blocks independent in the
random-XOF idealization, with maximum atom rho=14/256.

The blockwise nonuniform Schwartz-Zippel lemma then gives
    Pr[P != 0] >= product_i (1 - d_i rho)
for any nonzero witness polynomial P with block degree vector d.
All rational arithmetic below is exact.
"""
from __future__ import annotations

import json
import math
from decimal import Decimal, getcontext
from fractions import Fraction
from pathlib import Path

getcontext().prec = 100
ROOT = Path(__file__).resolve().parent
RHO = Fraction(14, 256)

PROFILES = [
    {
        "key": "L1-practical", "level": "I", "m1": 5, "s": 10,
        "core_blocks": 3, "loops": [5, 5, 5], "edges": [5, 5, 5],
        "slice_guarantee_by_dimensions": False,
        "guaranteed_projection_dimension_by_shape": [7, 7],
    },
    {
        "key": "L3-practical", "level": "III", "m1": 7, "s": 11,
        "core_blocks": 3, "loops": [7, 7, 0], "edges": [7, 7, 5],
        "slice_guarantee_by_dimensions": False,
        "guaranteed_projection_dimension_by_shape": [11, 9],
    },
    {
        "key": "L5-practical", "level": "V", "m1": 9, "s": 13,
        "core_blocks": 2, "loops": [9, 8], "edges": [9],
        "slice_guarantee_by_dimensions": True,
        "guaranteed_projection_dimension_by_shape": [13, 15],
    },
]


def dlog2(x: Fraction) -> Decimal:
    return (Decimal(x.numerator).ln() - Decimal(x.denominator).ln()) / Decimal(2).ln()


def degree_vector(m1: int, counts: list[int]) -> list[int]:
    """Each family contributes one row from base form i for all i<count."""
    return [sum(1 for c in counts if i < c) for i in range(m1)]


def record(p: dict) -> dict:
    counts = p["loops"] + p["edges"]
    deg = degree_vector(p["m1"], counts)
    assert sum(deg) == p["core_blocks"] * p["s"]
    factors = [1 - d * RHO for d in deg]
    if any(x <= 0 for x in factors):
        raise AssertionError((p["key"], deg, factors))
    beta = math.prod(factors, start=Fraction(1, 1))
    retry = 1 / beta
    return {
        **p,
        "active_family_row_counts": counts,
        "block_degree_vector": deg,
        "total_degree": sum(deg),
        "rho_numerator": RHO.numerator,
        "rho_denominator": RHO.denominator,
        "factor_numerators": [x.numerator for x in factors],
        "factor_denominators": [x.denominator for x in factors],
        "nonzero_probability_lower_numerator": beta.numerator,
        "nonzero_probability_lower_denominator": beta.denominator,
        "nonzero_probability_lower_decimal": float(beta),
        "log2_nonzero_probability_lower": float(dlog2(beta)),
        "weak_key_retry_upper_numerator": retry.numerator,
        "weak_key_retry_upper_denominator": retry.denominator,
        "weak_key_retry_upper_decimal": float(retry),
        "weak_key_retry_log2": float(dlog2(retry)),
    }


def main() -> None:
    rows = [record(p) for p in PROFILES]
    data = {
        "model": "random-XOF idealization of disjoint public-expansion bytes reduced modulo 19",
        "maximum_atom": {"numerator": RHO.numerator, "denominator": RHO.denominator},
        "lemma": (
            "If independent scalar coordinates are grouped into blocks X_i, each coordinate has maximum atom rho, "
            "and nonzero P has total degree at most d_i in block i, then Pr[P != 0] is at least product_i(1-d_i rho)."
        ),
        "scope": (
            "The determinant witness is pulled back through restriction of fresh internal symmetric forms to a "
            "projection-injective A-linear slice. The bound is conditional on the cross-data-selected slice passing "
            "that exact public projection preflight. Dimension alone guarantees such a slice for both Level-V shapes, "
            "for the first Level-III shape at s=11, but not for Level I or the second Level-III shape."
        ),
        "profiles": rows,
    }
    (ROOT / "preflight_anticoncentration.json").write_text(json.dumps(data, indent=2) + "\n")

    md = [
        "# Exact biased-product preflight anti-concentration certificate",
        "",
        "Generated by `build_preflight_anticoncentration.py`; all displayed probabilities are exact rational values.",
        "",
        "For a nonzero polynomial with degree at most `d_i` in independent coordinate block `i`, and maximum scalar atom `rho=14/256`, recursive nonuniform Schwartz-Zippel gives",
        "",
        "```text",
        "Pr[P != 0] >= product_i (1 - d_i rho).",
        "```",
        "",
        "The exact eigenblock witness proves that the selected core-Jacobian determinant is not the zero polynomial on the allowable symmetric-form space. Projection injectivity makes restriction from the fresh internal `P11` block onto that space surjective. The selected row assignment gives the per-base-form degrees below.",
        "",
        "| Level | core | per-form degree vector | lower bound | log2 lower bound | retry upper bound | dimension guarantee |",
        "|---:|:---:|:---|---:|---:|---:|:---|",
    ]
    for r in rows:
        guarantee = "both shapes" if r["slice_guarantee_by_dimensions"] else (
            "first shape only" if r["level"] == "III" else "public preflight"
        )
        md.append(
            f"| {r['level']} | {r['core_blocks']}x{r['s']} | `{r['block_degree_vector']}` | "
            f"{r['nonzero_probability_lower_numerator']}/{r['nonzero_probability_lower_denominator']} "
            f"= {r['nonzero_probability_lower_decimal']:.9f} | "
            f"{r['log2_nonzero_probability_lower']:.6f} | "
            f"{r['weak_key_retry_upper_decimal']:.4f} ({r['weak_key_retry_log2']:.4f} bits) | {guarantee} |"
        )
    md += [
        "",
        "## Scope and interpretation",
        "",
        "This is a theorem about a constant fraction of keys in the random-XOF idealization, not a claim that every fixed SHAKE seed passes. For any fixed key the determinant is public and can be tested exactly before the solver is run. The guarantee is unconditional with respect to projection-slice existence only where the conservative dimension bound reaches the selected `s`; elsewhere the public projection preflight remains explicit, and the full ordinary-slice attack is the fixed-core-free fallback.",
    ]
    (ROOT / "PREFLIGHT_ANTICONCENTRATION_CERTIFICATE.md").write_text("\n".join(md) + "\n")

    for r in rows:
        print(r["level"], r["block_degree_vector"], f"beta={r['nonzero_probability_lower_decimal']:.12f}", f"retrybits={r['weak_key_retry_log2']:.6f}")


if __name__ == "__main__":
    main()
